// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQAKLwwLEonXLcHyi-_7ZOrhBE8unIPdA',
    appId: '1:649307052685:web:43d7f323ef37b96837e0c4',
    messagingSenderId: '649307052685',
    projectId: 'test-6dec8',
    authDomain: 'test-6dec8.firebaseapp.com',
    storageBucket: 'test-6dec8.firebasestorage.app',
    measurementId: 'G-L23KPT60F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzNUh87Q63aL3ZLHsuX_8jcnfeKhteWjU',
    appId: '1:649307052685:android:e71074757e20fa1b37e0c4',
    messagingSenderId: '649307052685',
    projectId: 'test-6dec8',
    storageBucket: 'test-6dec8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAElwwPrPAmc3TyA1nkDpmXIG_m3jIQ-Sw',
    appId: '1:649307052685:ios:f3ad8d395204424a37e0c4',
    messagingSenderId: '649307052685',
    projectId: 'test-6dec8',
    storageBucket: 'test-6dec8.firebasestorage.app',
    iosBundleId: 'com.serdal.termini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAElwwPrPAmc3TyA1nkDpmXIG_m3jIQ-Sw',
    appId: '1:649307052685:ios:f3ad8d395204424a37e0c4',
    messagingSenderId: '649307052685',
    projectId: 'test-6dec8',
    storageBucket: 'test-6dec8.firebasestorage.app',
    iosBundleId: 'com.serdal.termini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQAKLwwLEonXLcHyi-_7ZOrhBE8unIPdA',
    appId: '1:649307052685:web:72b11c719b95e04437e0c4',
    messagingSenderId: '649307052685',
    projectId: 'test-6dec8',
    authDomain: 'test-6dec8.firebaseapp.com',
    storageBucket: 'test-6dec8.firebasestorage.app',
    measurementId: 'G-E0LBTY67GM',
  );
}
